jobs:
  include:
    - stage: No full
      script:
        - wget -O run https://raw.githubusercontent.com/minidocks/images/master/run
        - for version in $(sh ./build.sh --versions | grep -v 'full'); do sh ./run build texlive/$version --dir "."; done
        - docker login -u "$REGISTRY_LOGIN" -p "$REGISTRY_PASSWORD"
        - sh ./run push texlive
    - stage: Full 2018
      script:
        - wget -O run https://raw.githubusercontent.com/minidocks/images/master/run
        - sh ./run build texlive/2018-full --dir "."
        - docker login -u "$REGISTRY_LOGIN" -p "$REGISTRY_PASSWORD"
        - sh ./run push texlive
    - stage: Full 2019
      script:
        - wget -O run https://raw.githubusercontent.com/minidocks/images/master/run
        - sh ./run build texlive/2019-full --dir "."
        - sh ./run build texlive/full --dir "."
        - docker login -u "$REGISTRY_LOGIN" -p "$REGISTRY_PASSWORD"
        - sh ./run push texlive
